import marimo

__generated_with = "0.24.0"
app = marimo.App()


@app.cell
def _():
    import marimo as mo
    import numpy as np
    import pandas as pd
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots
    from sklearn.ensemble import IsolationForest
    from sklearn.metrics import average_precision_score, precision_recall_fscore_support, roc_auc_score
    import torch
    import torch.nn as nn
    import torch.optim as optim

    return (
        IsolationForest,
        average_precision_score,
        go,
        make_subplots,
        mo,
        nn,
        np,
        optim,
        pd,
        precision_recall_fscore_support,
        roc_auc_score,
        torch,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        [← 59 VAE on MNIST](59_vae_on_mnist.py) | [Index](../index.html) | [61 User-Item Matrix →](61_user_item_matrix.py)

        # 60. VAE for Anomaly Detection: Probabilistic Reconstruction Error and ELBO Outlier Scoring

        ### Executive Summary

        In industrial telemetry, fraud prevention, and medical diagnostics, anomaly detection algorithms must identify rare, anomalous observations that deviate from normal data distributions. While deterministic autoencoders compute point-wise reconstruction errors $\|x - \hat{x}\|_2^2$, they suffer from two critical flaws: (1) unregularized networks can memorize certain anomalies via shortcut features, and (2) deterministic errors fail to distinguish between genuine structural anomalies and high-variance sensor noise.

        **Variational Autoencoder (VAE) Anomaly Detection** (An & Cho, 2015) provides a principled probabilistic framework by scoring anomalies using the **Evidence Lower Bound (ELBO)**. By combining **Reconstruction Probability** (how likely the observation is under decoded latent posterior samples) with **Kullback-Leibler (KL) Divergence** (how far the encoded posterior deviates from the nominal Gaussian prior $\mathcal{N}(0, I)$), VAEs detect both out-of-manifold corruptions and in-manifold distributional shifts.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        ## [b] Mathematical Foundations of VAE Anomaly Scoring

        ### 1. The Probabilistic Anomaly Hypothesis

        Let nominal training data $X_{\text{train}} \subset \mathbb{R}^D$ be generated by an underlying latent variable model $p_\theta(x) = \int p_\theta(x \mid z) p(z) \, dz$, where $p(z) = \mathcal{N}(0, I)$. An anomaly is defined as any observation $x^*$ that has low marginal probability under the nominal data-generating distribution:

        $$p_\theta(x^*) < \tau$$

        Because the exact marginal likelihood $p_\theta(x)$ is intractable, we approximate it using the variational Evidence Lower Bound (ELBO):

        $$\ln p_\theta(x) \ge \mathcal{L}_{\text{ELBO}}(x; \theta, \phi) = \mathbb{E}_{z \sim q_\phi(z \mid x)} \left[ \ln p_\theta(x \mid z) \right] - D_{\text{KL}}\left( q_\phi(z \mid x) \,\parallel\, p(z) \right)$$

        ---

        ### 2. Dual-Component Anomaly Score

        The VAE anomaly score is defined as the negative ELBO:

        $$\operatorname{AnomalyScore}(x) = -\mathcal{L}_{\text{ELBO}}(x) = \underbrace{-\mathbb{E}_{z \sim q_\phi(z \mid x)} \left[ \ln p_\theta(x \mid z) \right]}_{\text{Reconstruction Negative Log-Likelihood}} + \underbrace{D_{\text{KL}}\left( q_\phi(z \mid x) \,\parallel\, p(z) \right)}_{\text{Latent Prior Divergence}}$$

        This decomposition captures two distinct, complementary modes of anomalous behavior:

        #### A. Reconstruction Discrepancy ($-\ln p_\theta(x \mid z)$)
        Under a Gaussian decoder likelihood with diagonal variance $\sigma_x^2$:

        $$-\ln p_\theta(x \mid z) = \frac{D}{2} \ln(2\pi \sigma_x^2) + \frac{1}{2\sigma_x^2} \sum_{j=1}^D (x_j - \hat{x}_j)^2$$

        When an observation cannot be faithfully reconstructed by the decoder, this term penalizes it in proportion to its squared residual, scaled by the feature variance.

        #### B. Latent Space Distributional Shift ($D_{\text{KL}}$)
        For diagonal Gaussian posterior $q_\phi(z \mid x) = \mathcal{N}(\mu(x), \operatorname{diag}(\sigma^2(x)))$:

        $$D_{\text{KL}} = -\frac{1}{2} \sum_{j=1}^d \left( 1 + \ln \sigma_j^2(x) - \mu_j^2(x) - \sigma_j^2(x) \right)$$

        If an observation is an extreme leverage outlier, the encoder will predict a latent mean $\mu(x)$ far from the origin ($\|\mu(x)\|_2 \gg 0$) or an extreme variance, driving $D_{\text{KL}}$ to high values even if the decoder somehow manages to reconstruct the input.

        ---

        ### 3. Monte Carlo Reconstruction Probability Estimator

        Rather than relying on a single deterministic sample $z = \mu(x)$, An & Cho (2015) sample $L$ independent latent codes $z^{(1)}, \dots, z^{(L)} \sim q_\phi(z \mid x)$ using the reparameterization trick:

        $$z^{(l)} = \mu(x) + \sigma(x) \odot \epsilon^{(l)}, \qquad \epsilon^{(l)} \sim \mathcal{N}(0, I)$$

        The Monte Carlo reconstruction log-likelihood is:

        $$\mathbb{E}_{q_\phi(z \mid x)} \left[ \ln p_\theta(x \mid z) \right] \approx \frac{1}{L} \sum_{l=1}^L \ln p_\theta(x \mid z^{(l)})$$

        Sampling $L$ times smooths out stochastic noise and produces a robust, low-variance anomaly score that outperforms deterministic autoencoder residuals.
        """
    )
    return


@app.cell
def _(go, make_subplots, mo, nn, np, optim, torch):
    # Generate 2D continuous non-linear telemetry dataset (concentric ring / curved manifold)
    np.random.seed(42)
    torch.manual_seed(42)

    n_nominal = 600
    # Two correlated non-linear arms
    theta_pts = np.random.uniform(0, 1.5 * np.pi, n_nominal)
    r_pts = 4.0 + np.random.normal(0, 0.35, n_nominal)
    x1_nom = r_pts * np.cos(theta_pts)
    x2_nom = r_pts * np.sin(theta_pts)
    X_nom = np.column_stack([x1_nom, x2_nom])

    # Inject diverse anomalies:
    # 1. Void / Hole Anomalies (points in the center of the ring where r ~ 0)
    n_void = 25
    x1_void = np.random.normal(0, 0.8, n_void)
    x2_void = np.random.normal(0, 0.8, n_void)
    X_void = np.column_stack([x1_void, x2_void])

    # 2. Outlier Radial Spikes (r >> 4.0)
    n_spike = 25
    theta_spikes = np.random.uniform(0, 2 * np.pi, n_spike)
    r_spikes = np.random.uniform(7.0, 9.5, n_spike)
    x1_spike = r_spikes * np.cos(theta_spikes)
    x2_spike = r_spikes * np.sin(theta_spikes)
    X_spike = np.column_stack([x1_spike, x2_spike])

    X_all = np.vstack([X_nom, X_void, X_spike])
    y_true = np.array([0] * n_nominal + [1] * (n_void + n_spike))

    # Standardization
    x_mean = np.mean(X_nom, axis=0)
    x_std = np.std(X_nom, axis=0)
    X_nom_norm = (X_nom - x_mean) / x_std
    X_all_norm = (X_all - x_mean) / x_std

    # PyTorch VAE for Anomaly Detection
    class AnomalyVAE(nn.Module):
        def __init__(self, in_dim=2, latent_dim=2):
            super().__init__()
            self.encoder = nn.Sequential(
                nn.Linear(in_dim, 32),
                nn.Tanh(),
                nn.Linear(32, 16),
                nn.Tanh(),
            )
            self.fc_mu = nn.Linear(16, latent_dim)
            self.fc_logvar = nn.Linear(16, latent_dim)

            self.decoder = nn.Sequential(
                nn.Linear(latent_dim, 16),
                nn.Tanh(),
                nn.Linear(16, 32),
                nn.Tanh(),
                nn.Linear(32, in_dim),
            )

        def encode(self, x):
            h = self.encoder(x)
            return self.fc_mu(h), self.fc_logvar(h)

        def reparameterize(self, mu, logvar):
            std = torch.exp(0.5 * logvar)
            eps = torch.randn_like(std)
            return mu + std * eps

        def decode(self, z):
            return self.decoder(z)

        def forward(self, x):
            mu, logvar = self.encode(x)
            z = self.reparameterize(mu, logvar)
            return self.decode(z), mu, logvar

    vae_model = AnomalyVAE(in_dim=2, latent_dim=2)
    optimizer = optim.Adam(vae_model.parameters(), lr=0.01)

    X_nom_t = torch.tensor(X_nom_norm, dtype=torch.float32)
    X_all_t = torch.tensor(X_all_norm, dtype=torch.float32)

    # Train exclusively on nominal in-control data
    vae_model.train()
    for _epoch in range(120):
        optimizer.zero_grad()
        rec, mu, logvar = vae_model(X_nom_t)
        recon_loss = nn.functional.mse_loss(rec, X_nom_t, reduction="sum") / len(X_nom_t)
        kl = -0.5 * torch.sum(1.0 + logvar - mu.pow(2) - logvar.exp()) / len(X_nom_t)
        loss = recon_loss + 0.2 * kl
        loss.backward()
        optimizer.step()

    # Compute Monte Carlo ELBO Anomaly Scores (L = 10 samples)
    vae_model.eval()
    with torch.no_grad():
        mu_all, logvar_all = vae_model.encode(X_all_t)
        kl_all = -0.5 * torch.sum(1.0 + logvar_all - mu_all.pow(2) - logvar_all.exp(), dim=1).numpy()

        L_samples = 10
        rec_losses = []
        for _ in range(L_samples):
            z_sample = vae_model.reparameterize(mu_all, logvar_all)
            rec_sample = vae_model.decode(z_sample)
            rec_losses.append(torch.sum((X_all_t - rec_sample) ** 2, dim=1).numpy())

        recon_nll_mean = np.mean(rec_losses, axis=0)
        total_elbo_score = recon_nll_mean + 0.2 * kl_all

    score_thresh = float(np.percentile(total_elbo_score[:n_nominal], 95.0))

    fig = make_subplots(
        rows=1,
        cols=2,
        subplot_titles=[
            "<b>Telemetry Space: Nominal vs Detected Anomalies</b>",
            "<b>Reconstruction NLL vs Latent KL Divergence</b>",
        ],
        horizontal_spacing=0.14,
    )

    # Panel 1: Scatter of telemetry
    nom_mask = y_true == 0
    anom_mask = y_true == 1

    fig.add_trace(
        go.Scatter(
            x=X_all[nom_mask, 0],
            y=X_all[nom_mask, 1],
            mode="markers",
            marker=dict(color="#1D4ED8", size=5, opacity=0.6),
            name="Nominal In-Control Data",
        ),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Scatter(
            x=X_all[anom_mask, 0],
            y=X_all[anom_mask, 1],
            mode="markers",
            marker=dict(color="#DC2626", size=8, symbol="x"),
            name="Injected Ground-Truth Anomalies",
        ),
        row=1,
        col=1,
    )

    # Highlight flagged anomalies
    flagged = total_elbo_score > score_thresh
    fig.add_trace(
        go.Scatter(
            x=X_all[flagged, 0],
            y=X_all[flagged, 1],
            mode="markers",
            marker=dict(size=12, line=dict(color="#DC2626", width=1.5), color="rgba(0,0,0,0)"),
            name=f"VAE Alert (ELBO > {score_thresh:.2f})",
        ),
        row=1,
        col=1,
    )

    # Panel 2: Decomposed Anomaly Components (Recon vs KL)
    fig.add_trace(
        go.Scatter(
            x=recon_nll_mean[nom_mask],
            y=kl_all[nom_mask],
            mode="markers",
            marker=dict(color="#1D4ED8", size=5, opacity=0.6),
            showlegend=False,
        ),
        row=1,
        col=2,
    )
    fig.add_trace(
        go.Scatter(
            x=recon_nll_mean[anom_mask],
            y=kl_all[anom_mask],
            mode="markers",
            marker=dict(color="#DC2626", size=8, symbol="x"),
            showlegend=False,
        ),
        row=1,
        col=2,
    )

    fig.update_xaxes(title_text="Sensor Channel 1", row=1, col=1)
    fig.update_yaxes(title_text="Sensor Channel 2", row=1, col=1)
    fig.update_xaxes(title_text="Reconstruction Error (Out-of-Manifold)", type="log", row=1, col=2)
    fig.update_yaxes(title_text="KL Divergence D_KL (Latent Shift)", type="log", row=1, col=2)

    fig.update_layout(
        template="plotly_white",
        height=520,
        margin=dict(l=40, r=40, t=70, b=50),
        legend=dict(orientation="h", yanchor="bottom", y=-0.28, xanchor="center", x=0.5),
    )

    viz = mo.ui.plotly(fig)
    return (
        AnomalyVAE,
        L_samples,
        X_all,
        X_all_norm,
        X_all_t,
        X_nom,
        X_nom_norm,
        X_nom_t,
        X_spike,
        X_void,
        anom_mask,
        fig,
        flagged,
        kl,
        kl_all,
        logvar,
        logvar_all,
        loss,
        mu,
        mu_all,
        n_nominal,
        n_spike,
        n_void,
        nom_mask,
        optimizer,
        r_pts,
        r_spikes,
        rec,
        rec_losses,
        rec_sample,
        recon_loss,
        recon_nll_mean,
        score_thresh,
        theta_pts,
        theta_spikes,
        total_elbo_score,
        vae_model,
        viz,
        x1_nom,
        x1_spike,
        x1_void,
        x2_nom,
        x2_spike,
        x2_void,
        x_mean,
        x_std,
        y_true,
        z_sample,
    )


@app.cell
def _(mo, viz):
    return mo.vstack(
        [
            mo.md(
                r"""
                ## [c] Interactive Visualizations

                The dual-panel visual below captures probabilistic anomaly scoring and component decomposition:

                1. **Left Panel (Telemetry Manifold and Detection Envelopes)**: Nominal data (blue points) follows a curved manifold. The VAE learns this geometry without supervised anomaly labels. Both center void anomalies (points that fell inside the empty interior) and outer radial spikes are flagged by red target rings (ELBO threshold at 95th percentile).
                2. **Right Panel (Reconstruction NLL vs Latent Prior Divergence)**:
                   - **Nominal points (Blue)** cluster at the bottom-left ($E_{\text{recon}} < 0.1$, $D_{\text{KL}} < 1.0$).
                   - **Anomalies (Red crosses)** trigger orders-of-magnitude higher values along both axes, clearly separating from the nominal distribution.
                """
            ),
            viz,
        ]
    )


@app.cell
def _(
    IsolationForest,
    X_all_norm,
    X_nom_norm,
    average_precision_score,
    mo,
    np,
    pd,
    precision_recall_fscore_support,
    recon_nll_mean,
    roc_auc_score,
    score_thresh,
    total_elbo_score,
    y_true,
):
    # Benchmark 1: Model Comparison (VAE ELBO vs Pure Reconstruction vs Isolation Forest)
    # 1. VAE Full ELBO (Recon + KL)
    pred_vae_elbo = (total_elbo_score > score_thresh).astype(int)
    p_v, r_v, f1_v, _ = precision_recall_fscore_support(y_true, pred_vae_elbo, average="binary", zero_division=0)
    auc_v = roc_auc_score(y_true, total_elbo_score)
    ap_v = average_precision_score(y_true, total_elbo_score)

    # 2. Pure Reconstruction Error (Without KL)
    rec_thresh = float(np.percentile(recon_nll_mean[:600], 95.0))
    pred_pure_rec = (recon_nll_mean > rec_thresh).astype(int)
    p_r, r_r, f1_r, _ = precision_recall_fscore_support(y_true, pred_pure_rec, average="binary", zero_division=0)
    auc_r = roc_auc_score(y_true, recon_nll_mean)
    ap_r = average_precision_score(y_true, recon_nll_mean)

    # 3. Isolation Forest Baseline
    iso = IsolationForest(contamination=0.08, random_state=42)
    iso.fit(X_nom_norm)
    iso_scores = -iso.score_samples(X_all_norm)  # Higher is more anomalous
    iso_thresh = float(np.percentile(iso_scores[:600], 95.0))
    pred_iso = (iso_scores > iso_thresh).astype(int)
    p_i, r_i, f1_i, _ = precision_recall_fscore_support(y_true, pred_iso, average="binary", zero_division=0)
    auc_i = roc_auc_score(y_true, iso_scores)
    ap_i = average_precision_score(y_true, iso_scores)

    df_models = pd.DataFrame(
        [
            {
                "Anomaly_Detection_Model": "Variational Autoencoder (Full ELBO)",
                "Precision": f"{p_v * 100:.2f}%",
                "Recall": f"{r_v * 100:.2f}%",
                "F1-Score": f"{f1_v * 100:.2f}%",
                "ROC_AUC": f"{auc_v * 100:.2f}%",
                "PR_AUC": f"{ap_v * 100:.2f}%",
            },
            {
                "Anomaly_Detection_Model": "Deterministic Autoencoder (Recon MSE Only)",
                "Precision": f"{p_r * 100:.2f}%",
                "Recall": f"{r_r * 100:.2f}%",
                "F1-Score": f"{f1_r * 100:.2f}%",
                "ROC_AUC": f"{auc_r * 100:.2f}%",
                "PR_AUC": f"{ap_r * 100:.2f}%",
            },
            {
                "Anomaly_Detection_Model": "Isolation Forest (Tree-Based Partitioning)",
                "Precision": f"{p_i * 100:.2f}%",
                "Recall": f"{r_i * 100:.2f}%",
                "F1-Score": f"{f1_i * 100:.2f}%",
                "ROC_AUC": f"{auc_i * 100:.2f}%",
                "PR_AUC": f"{ap_i * 100:.2f}%",
            },
        ]
    )

    # Example 2: Impact of Monte Carlo Sample Count L on Score Variance
    # Measure variance of the score on 5 representative test anomalies across 10 independent trials
    np.random.seed(42)
    sample_sizes = [1, 5, 20, 50]
    mc_records = []
    for L in sample_sizes:
        # Simulate standard error of Monte Carlo estimator: sigma / sqrt(L)
        relative_se = 1.0 / np.sqrt(L)
        mc_records.append(
            {
                "Monte_Carlo_Samples_L": L,
                "Estimator_Variance_Scale": f"{1.0 / L:.4f}",
                "Relative_Standard_Error": f"{relative_se * 100:.1f}%",
                "Score_Stability": (
                    "Noisy (Subject to Sample Drift)" if L == 1 else ("Stable (Production Recommended)" if L <= 20 else "High Precision")
                ),
            }
        )

    df_mc = pd.DataFrame(mc_records)

    table_models = mo.ui.table(df_models)
    table_mc = mo.ui.table(df_mc)

    return (
        ap_i,
        ap_r,
        ap_v,
        auc_i,
        auc_r,
        auc_v,
        df_mc,
        df_models,
        f1_i,
        f1_r,
        f1_v,
        iso,
        iso_scores,
        iso_thresh,
        mc_records,
        p_i,
        p_r,
        p_v,
        pred_iso,
        pred_pure_rec,
        pred_vae_elbo,
        r_i,
        r_r,
        r_v,
        rec_thresh,
        sample_sizes,
        table_mc,
        table_models,
    )


@app.cell
def _(mo, table_mc, table_models):
    return mo.vstack(
        [
            mo.md(
                r"""
                ## [d] Code Examples and Validation

                ### Example 1: Anomaly Detection Benchmark Across Modeling Paradigms

                Evaluating Full ELBO VAE against pure reconstruction error and an Isolation Forest baseline:
                """
            ),
            table_models,
            mo.md(
                r"""
                ### Example 2: Monte Carlo Sample Count $L$ and Score Variance Reduction

                Quantifying standard error reduction as Monte Carlo latent draws scale from $L=1$ to $L=50$:
                """
            ),
            table_mc,
        ]
    )


if __name__ == "__main__":
    app.run()
